# Generated by Django 4.2.5 on 2023-10-05 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hemis_admin', models.BooleanField(default=False)),
                ('is_moodle_admin', models.BooleanField(default=False)),
                ('is_kerocontrol_admin', models.BooleanField(default=False)),
                ('selected_admin', models.CharField(blank=True, choices=[('hemis', 'Hemis'), ('moodle', 'Moodle'), ('kerocontrol', 'Kerocontrol')], max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_self_visible', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Erkak'), (2, 'Ayol')], null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
