# Generated by Django 4.2.6 on 2023-10-10 02:08

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[users.validators.validate_passport_serial]),
        ),
    ]
