# Generated by Django 4.2.6 on 2023-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_application_faculty_kafedra_position_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
