# Generated by Django 4.2.5 on 2024-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_application_group_remove_application_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincreate',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
