# Generated by Django 4.2.5 on 2023-11-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_positionone_bolim_positionone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='kerocontrol',
        ),
        migrations.AddField(
            model_name='kerocontrol',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.building'),
        ),
    ]
