# Generated by Django 4.2.5 on 2024-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_logincreate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
