# Generated by Django 4.2.5 on 2023-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_building_kerocontrol_kerocontrol_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_admin',
            field=models.CharField(blank=True, choices=[('hemis', 'Hemis'), ('lms', 'LMS'), ('kerocontrol', 'Kerocontrol')], max_length=20, null=True),
        ),
    ]
