# Generated by Django 4.2.5 on 2023-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_selected_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_hemis_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_kerocontrol_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_moodle_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
