# Generated by Django 4.2.5 on 2023-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_is_hemis_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_self_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
