# Generated by Django 4.2.5 on 2023-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_is_admin_alter_profile_is_self_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Tekshirilmoqda'), ('published', 'Tekshirildi')], default='draft', max_length=10),
        ),
    ]
