# Generated by Django 4.2.5 on 2023-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('tekshirilmoqda', 'Tekshirilmoqda'), ('tekshirildi', 'Tekshirildi')], default='tekshirilmoqda', max_length=14),
        ),
    ]
