# Generated by Django 4.2.5 on 2023-11-17 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lest_name',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/image'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/passport'),
        ),
    ]
