# Generated by Django 4.2.5 on 2023-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_application_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/image/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/passport/'),
        ),
    ]
