# Generated by Django 4.2.5 on 2023-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_application_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcreate',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
