# Generated by Django 4.2.5 on 2023-11-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_applicationcreate_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolim',
            name='position',
        ),
        migrations.RemoveField(
            model_name='hemis',
            name='system',
        ),
        migrations.RemoveField(
            model_name='kerocontrol',
            name='system',
        ),
        migrations.RemoveField(
            model_name='lms',
            name='system',
        ),
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
