# Generated by Django 4.2.5 on 2023-11-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_passport/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('tekshirilmoqda', 'Tekshirilmoqda'), ('rad etildi', 'Rad etildi'), ('tekshirildi', 'Tekshirildi')], default='tekshirilmoqda', max_length=14),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
