# Generated by Django 4.2.6 on 2023-12-18 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hemis_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_lms_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_kerocontrol_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_self_visible', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_avatar', models.ImageField(blank=True, null=True, upload_to='admin/profiles/')),
                ('back_admin_avatar', models.ImageField(blank=True, null=True, upload_to='admin/back/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport_serial', models.CharField(blank=True, max_length=9, null=True, validators=[users.validators.validate_passport_serial])),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Erkak'), (2, 'Ayol')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
