# Generated by Django 4.2.6 on 2023-12-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_users',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
