# Generated by Django 4.2.6 on 2024-01-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adminprofile_is_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='back_admin_avatar',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_users',
        ),
    ]
