# Generated by Django 4.2.6 on 2024-02-08 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_remove_adminprofile_back_admin_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='fayllar/')),
                ('tasdiq_soni', models.IntegerField(default=0)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_admin_kafedra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_admin_oquv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_admin_talim',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='FaylTasdiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasdiq_vaqt', models.DateTimeField(auto_now_add=True)),
                ('tasdiq_holati', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fayl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.fayl')),
            ],
        ),
        migrations.AddField(
            model_name='fayl',
            name='filetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.filetype'),
        ),
    ]
