# Generated by Django 4.2.6 on 2024-02-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_back_avatar'),
        ('dashboard', '0004_fayl_filetype_adminprofile_is_admin_kafedra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fayl',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='filetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fayl_type', to='dashboard.filetype'),
        ),
    ]
