# Generated by Django 4.2.6 on 2024-02-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_back_avatar'),
        ('dashboard', '0005_fayl_faculty_alter_fayl_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fayl',
            name='kafedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kafedra', to='users.kafedra'),
        ),
    ]
