# Generated by Django 4.2.6 on 2024-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_fayl_kafedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fayl',
            name='tasdiq_soni',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
