# Generated by Django 4.2.6 on 2024-02-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_back_avatar'),
        ('dashboard', '0007_alter_fayl_tasdiq_soni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('kafedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kafedra')),
            ],
        ),
        migrations.AddField(
            model_name='fayl',
            name='authn',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='dashboard.author'),
        ),
    ]
