# Generated by Django 4.2.6 on 2024-02-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_fayl_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fayltasdiq',
            name='admin_tekshirish_vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
