# Generated by Django 4.2.6 on 2024-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_fayltasdiq_admin_tekshirish_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fayl',
            name='authn',
            field=models.ManyToManyField(blank=True, related_name='author', to='dashboard.author'),
        ),
    ]
