# Generated by Django 4.2.6 on 2024-02-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_fayl_authn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fayl',
            name='admin',
        ),
    ]
