# Generated by Django 4.2.6 on 2024-02-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_fayl_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fayl',
            name='admin_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
