# Generated by Django 4.2.6 on 2024-02-12 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_fayl_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fayl',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='fayl',
            name='admin_username',
        ),
        migrations.AddField(
            model_name='fayl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
