# Generated by Django 4.2.6 on 2024-02-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_fayl_admin_remove_fayl_admin_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fayl',
            name='user',
        ),
        migrations.AddField(
            model_name='fayl',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adminprofile'),
        ),
    ]
