# Generated by Django 4.2.6 on 2024-02-12 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_remove_fayl_user_fayl_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fayl',
            name='admin',
        ),
        migrations.AddField(
            model_name='fayl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
