# Generated by Django 4.2.6 on 2024-02-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_fayl_admin_fayl_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fayl',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='fayl',
            name='tasdiq_soni',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adminprofile'),
        ),
        migrations.AlterField(
            model_name='fayltasdiq',
            name='tasdiq_holati',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
