# Generated by Django 4.2.6 on 2024-02-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_alter_fayl_options_alter_fayl_tasdiq_soni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fayl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
