# Generated by Django 4.2.5 on 2024-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_fayl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_kerocontrol2_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_kerocontrol3_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
